System hostname = test.privacy.fish

Which network interface do you wish to configure = vio0
IPv4 address for vio0 = 85.137.228.93
Netmask for IPv4 address for vio0 = 255.255.255.0
Default IPv4 route = 85.137.228.1
IPv6 address for vio0 = none

DNS domain name = privacy.fish
DNS nameserver = 9.9.9.9

Password for root = *************
Public ssh key for root account = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIED3Z5dY7J9gvLYSDLkKPlSE7MJHZrt7SwOWUh7ABTtO p.thurner@blunix.com

Start sshd(8) by default = yes
Allow root ssh login = prohibit-password
Setup a user = no

What timezone are you in = UTC

Use (W)hole disk MBR, whole disk (G)PT, (O)penBSD area or (E)dit = W
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = A

Location of sets = http
HTTP Server = cdn.openbsd.org
Set name(s) = -comp* -game* -x*

Do you expect to run the X Window System = no
